export const REQ_REGISTER = 'REQ_REGISTER';
export const REQ_REGISTER_SUCCESS = 'REQ_REGISTER_SUCCESS';
export const REQ_REGISTER_FAILED = 'REQ_REGISTER_FAILED';

export const REQ_LOGIN = 'REQ_LOGIN';
export const REQ_LOGIN_SUCCESS = 'REQ_LOGIN_SUCCESS';
export const REQ_LOGIN_FAILED = 'REQ_LOGIN_FAILED';

export const REQ_USER_DATA = 'REQ_USER_DATA';
export const REQ_USER_DATA_SUCCESS = 'REQ_USER_DATA_SUCCESS';
export const REQ_USER_DATA_FAILED = 'REQ_USER_DATA_FAILED';

export const CONNECT_SOCKET = 'CONNECT_SOCKET';

export const STORE_ACTIVE_ROOMS = 'STORE_ACTIVE_ROOMS';
export const UPDATE_ACTIVE_ROOMS = 'UPDATE_ACTIVE_ROOMS';
export const ADD_ACTIVE_ROOM = 'ADD_ACTIVE_ROOM';

export const STORE_ROOM_MESSAGES = 'STORE_ROOM_MESSAGES';
export const STORE_NEW_MESSAGE = 'STORE_NEW_MESSAGE';
